//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWriter.OpenLiveWriter.BlogClient.Clients {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BlogClientLoginDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlogClientLoginDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlogWriter.OpenLiveWriter.BlogClient.Clients.BlogClientLoginDialog", typeof(BlogClientLoginDialog).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes blogClientLoginControl_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("blogClientLoginControl.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool blogClientLoginControl_Locked {
            get {
                object obj = ResourceManager.GetObject("blogClientLoginControl.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes blogClientLoginControl_Modifiers {
            get {
                object obj = ResourceManager.GetObject("blogClientLoginControl.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes buttonCancel_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool buttonCancel_Locked {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes buttonCancel_Modifiers {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes buttonOK_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("buttonOK.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool buttonOK_Locked {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes buttonOK_Modifiers {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
